import Image from "next/image";
import Link from "next/link";
import { BadgeCheck, Calculator, CircleGauge, FileText, Ruler, ShieldCheck } from "lucide-react";
import { ContactCta } from "@/components/contact-cta";
import { MotionSection } from "@/components/motion-section";
import { SectionKicker } from "@/components/section-kicker";
import { SiteHeader } from "@/components/site-header";
import { SteelTestingProof } from "@/components/steel-testing-proof";
import { createPageMetadata, productionDomain } from "@/lib/site-metadata";

const heroImage = "/ars-assets/Sizes/16mm_Banner.jpg";
const detailImage = "/ars-assets/Sizes/16mm-detail.png";
const faqs = [
  ["What is the 16mm steel bar weight per metre?", "The typical weight of 16mm TMT bar is usually about 1.580 kg per metre. This substantial weight contributes significantly to the stability and load-bearing capacity of structures, making it ideal for heavy-duty construction projects."],
  ["Why are 16mm steel bars recommended for large structural applications?", "16mm TMT bars are particularly useful for large structures because their thickness provides exceptional strength and durability, essential for supporting heavy loads and high stresses. This makes them ideal for critical components like foundation slabs, beams, and columns in large buildings, as well as infrastructure such as bridges and highways."],
  ["How does the length of a 16mm steel bar affect its application in construction?", "The length of a 16mm steel bar can vary based on project specifications, but commonly used lengths ensure comprehensive coverage and reinforcement in large areas. Longer bars reduce the need for overlapping joints, enhancing structural integrity and reducing weak points in construction."],
  ["What are the factors that affect 16mm steel bar price?", "The 16mm steel bar price is typically influenced by factors such as market demand, raw material costs, and availability. However, their efficiency in use and the reduction in required quantities due to their strength often result in cost savings in large-scale projects."],
  ["How does the weight of a 16mm TMT bar contribute to safety and longevity?", "The 16mm steel rod weight enhances the safety and longevity of buildings by providing superior resistance to natural forces such as earthquakes and weather conditions. Their high tensile strength and ductility help maintain structural integrity under stress, reducing the risk of failures and extending the lifespan of the construction."],
] as const;
export const metadata = createPageMetadata({ title: "16mm Steel Rod | ARS Green Steel", description: "ARS 16mm TMT steel rods for heavy-duty structural construction. Approximate nominal weight: 1.580 kg per metre.", path: "/16-mm-steel-rod", image: heroImage });

export default function SixteenMmSteelRodPage() {
  const productJsonLd = { "@context": "https://schema.org", "@type": "Product", name: "ARS 16mm Steel Rod", description: "ARS 16mm TMT steel bar for heavy-duty structural applications.", image: `${productionDomain}${heroImage}`, brand: { "@type": "Brand", name: "ARS Green Steel" }, additionalProperty: [{ "@type": "PropertyValue", name: "Nominal diameter", value: "16 mm" }, { "@type": "PropertyValue", name: "Approximate weight per metre", value: "1.580 kg/m" }] };
  const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  return <main className="min-h-screen overflow-x-clip bg-surface-50 text-ink-900"><SiteHeader /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
    <section className="ars-page-hero relative flex min-h-[560px] items-end overflow-hidden bg-ink-950 md:min-h-[600px] lg:h-[680px] lg:min-h-[680px] lg:max-h-[680px]"><Image src={heroImage} alt="ARS 16mm TMT steel reinforcement bar" fill priority sizes="100vw" className="object-cover object-[63%_center]" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,13,30,0.74)_0%,rgba(6,13,30,0.54)_48%,rgba(6,13,30,0.14)_100%)] md:bg-[linear-gradient(90deg,rgba(6,13,30,0.64)_0%,rgba(6,13,30,0.34)_48%,rgba(6,13,30,0.03)_100%)]" /><div className="absolute inset-x-0 bottom-0 h-[58%] bg-[linear-gradient(0deg,rgba(6,13,30,0.38)_0%,rgba(6,13,30,0.08)_58%,transparent_100%)] md:h-[48%] md:bg-[linear-gradient(0deg,rgba(6,13,30,0.24)_0%,rgba(6,13,30,0.04)_58%,transparent_100%)]" /><div className="ars-container relative z-10 w-full pb-14 md:pb-16"><div className="max-w-3xl"><SectionKicker variant="light">ARS TMT BAR SIZES</SectionKicker><h1 className="mt-5 font-display text-[clamp(2.65rem,6vw,4.5rem)] font-extrabold uppercase leading-[1] tracking-[-0.025em] text-white">Build with Confidence: ARS 16MM Steel Rod Weight vis-à-vis Strength is Unbeatable!</h1><p className="mt-5 max-w-2xl text-[15px] leading-[1.75] text-white/78">Leverage the advantage of ARS 16MM steel bar weight per metre for substantial structural applications such as commercial foundations, large load-bearing beams, and heavy-duty bridges.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/tmt-steel-price-today" className="focus-ring inline-flex min-h-12 items-center gap-2.5 rounded-full bg-brand-red px-6 py-3 text-[14px] font-bold text-white"><Calculator size={15} /> Check price</Link><Link href="/request-quote" className="focus-ring inline-flex min-h-12 items-center gap-2.5 rounded-full border border-white/35 px-6 py-3 text-[14px] font-bold text-white"><FileText size={15} /> Request a quote</Link></div></div></div></section>
    <MotionSection className="border-b border-surface-100 bg-white py-10"><div className="ars-container grid grid-cols-2 gap-y-7 lg:grid-cols-4 lg:gap-0 lg:divide-x lg:divide-ink-900/10">{[["16 mm","Nominal diameter",Ruler],["1.580 kg/m","Approx. weight per metre",CircleGauge],["TMT","Reinforcement steel",ShieldCheck],["SGS","Certified assurance",BadgeCheck]].map(([value,label,Icon]) => { const I=Icon as typeof Ruler; return <div key={String(label)} className="px-0 lg:px-8 lg:text-center"><I size={16} className="mb-2 text-brand-red lg:mx-auto" /><p className="font-display text-[1.55rem] font-extrabold text-brand-blue">{String(value)}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.1em] text-ink-900">{String(label)}</p></div>})}</div></MotionSection>
    <MotionSection className="bg-white py-20 md:py-24"><div className="ars-container grid gap-12 lg:grid-cols-[0.92fr_1.08fr] lg:items-center lg:gap-16"><div className="relative min-h-[420px] overflow-hidden rounded-[8px] bg-ink-950"><Image src={detailImage} alt="ARS 16mm steel bar detail" fill sizes="(max-width:1024px) 100vw,45vw" className="object-cover" /></div><div><SectionKicker variant="brand">PRODUCT OVERVIEW</SectionKicker><h2 className="font-display text-[clamp(2rem,3.4vw,2.5rem)] font-bold leading-[1.1] text-ink-900">Master Heavy-Duty Construction with the Perfect ARS 16MM Steel Bar Weight</h2><p className="mt-6 text-[15px] leading-[1.8] text-steel-700">Unlock the potential of the 16mm steel bar from ARS Steels, tailored for heavy-duty construction where strength and resilience are non-negotiable. With an approximate weight of 1.580 kg per metre, these bars suit foundations, high-rise columns, bridges, and highways.</p><div className="mt-8 overflow-hidden border border-surface-100">{[["Nominal diameter","16 mm"],["Approximate weight per metre","1.580 kg/m"],["Ideal applications","Foundations, high-rise columns, bridges, highways"]].map(([l,v],i)=><div key={l} className={`grid grid-cols-5 gap-4 px-5 py-4 ${i%2===0?'bg-surface-50':'bg-white'}`}><p className="col-span-2 text-[10px] font-bold uppercase tracking-[.08em] text-brand-blue">{l}</p><p className="col-span-3 text-[13px] text-steel-700">{v}</p></div>)}</div></div></div></MotionSection>
    <MotionSection className="bg-brand-blue py-20 md:py-24"><div className="ars-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionKicker variant="light">ARS STEEL BENEFITS</SectionKicker><h2 className="font-display text-[clamp(2rem,3.4vw,2.5rem)] font-bold leading-[1.1] text-white">Quality built for demanding loads.</h2></div><div className="space-y-8"><article className="border-l-2 border-brand-red pl-6"><h3 className="font-display text-[1.35rem] font-bold text-white">Commitment to ‘D’ Quality Expertise</h3><p className="mt-3 text-[14px] leading-[1.8] text-white/75">At ARS Steels, our dedication to superior craftsmanship is embodied in our ‘D’ Quality expertise. The high 16mm TMT bar weight is crafted with meticulous attention to detail, ensuring rigorous strength, durability, and flexibility criteria.</p></article><article className="border-l-2 border-brand-red pl-6"><h3 className="font-display text-[1.35rem] font-bold text-white">SGS Certified Assurance</h3><p className="mt-3 text-[14px] leading-[1.8] text-white/75">ARS Steels takes pride in quality and reliability confirmed through SGS certification, providing confidence that every 16mm steel TMT bar is rigorously tested for safety and excellence.</p></article></div></div></MotionSection>
    <MotionSection className="bg-surface-50 py-20 md:py-24"><div className="ars-container grid gap-12 lg:grid-cols-[1fr_.8fr]"><div><SectionKicker variant="brand">16 MM USE CASES</SectionKicker><h2 className="font-display text-[clamp(2rem,3.4vw,2.5rem)] font-bold leading-[1.1] text-ink-900">Made for major structures and enduring loads.</h2><p className="mt-6 text-[15px] leading-[1.8] text-steel-700">16mm TMT steel bars are crucial in high-rise buildings, large commercial complexes, and heavy infrastructure such as bridges and highways. Their substantial diameter is suited to foundational works and major structural beams that support significant weight and stress.</p><p className="mt-5 text-[15px] leading-[1.8] text-steel-700">They are also selected for projects requiring long spans and heavy loads, including industrial floors, dams, and water treatment facilities.</p></div><aside className="border-t-2 border-brand-blue bg-white p-7"><p className="font-technical text-[11px] font-bold uppercase tracking-[.14em] text-brand-blue">Common applications</p><ul className="mt-6 space-y-4">{["High-rise buildings and commercial complexes","Foundation slabs, structural beams, and columns","Bridges, highways, and heavy infrastructure","Industrial floors, dams, and water treatment facilities"].map(x=><li key={x} className="flex gap-3 text-[14px] leading-[1.6] text-steel-700"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-red" />{x}</li>)}</ul></aside></div></MotionSection>
    <SteelTestingProof />
    <MotionSection className="bg-surface-50 py-20 md:py-24"><div className="ars-container grid gap-10 lg:grid-cols-[.62fr_1.38fr]"><div><SectionKicker variant="brand">FAQS</SectionKicker><h2 className="font-display text-[clamp(2rem,3.4vw,2.5rem)] font-bold leading-[1.1] text-ink-900">16mm steel bar questions, answered.</h2></div><div className="divide-y divide-ink-900/10 border-y border-ink-900/10">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="focus-ring cursor-pointer list-none pr-8 text-[15px] font-bold text-ink-900">{q}<span className="float-right text-brand-red">+</span></summary><p className="pt-4 pr-8 text-[14px] leading-[1.75] text-steel-700">{a}</p></details>)}</div></div></MotionSection>
    <ContactCta eyebrow="Plan with precision" headline="Need 16mm steel for your project?" body="Check the latest ARS steel price, find an authorised dealer, or request support for your construction requirement." primaryLabel="Check price" primaryHref="/tmt-steel-price-today" secondaryLabel="Find a dealer" secondaryHref="/our-network" /></main>;
}
