import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPin, ShieldCheck } from "lucide-react";
import { ContactCta } from "@/components/contact-cta";
import { MotionSection } from "@/components/motion-section";
import { SectionKicker } from "@/components/section-kicker";
import { SiteHeader } from "@/components/site-header";
import { createPageMetadata } from "@/lib/site-metadata";

export const metadata: Metadata = createPageMetadata({ title: "ARS Steel Rot Buy Now | ARS Green Steel", description: "Explore ARS CRS Fe 550D corrosion-resistant TMT steel and connect with ARS for buying support.", path: "/arssteel-rot-buynow", image: "/ars-assets/products/ARS-CRS550D_hero-banner.jpg" });

const points = ["ARS CRS Fe 550D can increase the life of any structure under specific conditions.", "550D CRS is highly recommended if the salt content in ground water is >300 ppm.", "Seaside structures benefit from reduced chloride-ion diffusion in TMT bars.", "Higher corrosion resistance, ductility, strength, concrete bonding, durability, and fire resistance."];

export default function ArsSteelRotBuyNowPage() {
  return <main className="min-h-screen overflow-x-clip bg-surface-50 text-ink-900"><SiteHeader />
    <section className="ars-page-hero relative flex min-h-[560px] items-end overflow-hidden bg-ink-950 text-white md:min-h-[600px] lg:h-[680px] lg:min-h-[680px]"><div className="absolute inset-0"><Image src="/ars-assets/products/ARS-CRS550D_hero-banner.jpg" alt="ARS CRS Fe 550D corrosion-resistant TMT steel" fill priority sizes="100vw" className="object-cover object-[60%_center]" /><div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(6,13,30,0.96),rgba(6,13,30,0.72)_52%,rgba(6,13,30,0.28))]" /><div className="absolute inset-0 bg-[linear-gradient(to_top,rgba(6,13,30,0.92),transparent_60%)]" /></div><div className="ars-container relative z-10 w-full pb-16 pt-32"><div className="max-w-4xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-white/75"><MapPin size={13} className="text-brand-red" aria-hidden="true" />ARS Steel</div><h1 className="max-w-4xl font-display text-[clamp(2.65rem,6vw,4.5rem)] font-extrabold leading-[1] tracking-[-0.025em] text-white">ARS Steel Rot Buy Now</h1><p className="mt-6 max-w-2xl text-[15px] leading-[1.8] text-white/75">Explore corrosion-resistant ARS CRS Fe 550D TMT reinforcement steel and connect with ARS for buying support.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/request-quote" className="focus-ring inline-flex min-h-12 items-center gap-2 rounded-full bg-brand-red px-6 py-3 text-sm font-bold text-white transition hover:opacity-90">Request a quote <ArrowRight size={16} /></Link><Link href="/our-network" className="focus-ring inline-flex min-h-12 items-center gap-2 rounded-full border border-white/35 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white hover:text-ink-900">Find a dealer <MapPin size={16} /></Link></div></div></div></section>
    <MotionSection className="border-b border-surface-100 bg-white py-9"><div className="ars-container grid gap-5 sm:grid-cols-3">{[["ARS CRS Fe 550D", "Corrosion-resistant TMT steel"], ["16–18%", "Ductility range stated in source"], ["CRE 0.5%", "Average corrosion resistance equivalent"]].map(([value, label]) => <div key={label} className="border-l-2 border-brand-red pl-5"><p className="font-display text-2xl font-extrabold text-brand-blue">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[0.08em] text-grey-600">{label}</p></div>)}</div></MotionSection>
    <MotionSection className="bg-white py-20 md:py-24"><div className="ars-container grid items-center gap-12 lg:grid-cols-[0.92fr_1.08fr] lg:gap-16"><div><SectionKicker variant="brand">CORROSION RESISTANCE</SectionKicker><h2 className="mt-3 font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08] text-ink-900">Join the Corrosion Resistance movement. ARS CRS Fe 550D is here!</h2><p className="mt-5 text-[15px] leading-[1.8] text-steel-700">It is here. A TMT Bar that retains its ductility while being corrosion and earthquake resistant. All thanks to the micro alloys, Copper, Chromium, Nickel and Molybdenum, added to the steel at optimal quantities.</p><ul className="mt-7 grid gap-4">{points.map((point) => <li key={point} className="flex gap-3 text-[14px] leading-[1.7] text-steel-700"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-brand-red" aria-hidden="true" />{point}</li>)}</ul></div><div className="relative min-h-[360px] overflow-hidden rounded-2xl bg-ink-950"><Image src="/ars-assets/products/WhatAre_ARS-CRS-550D_TMTBars.jpg" alt="ARS CRS Fe 550D TMT reinforcement bars" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div></div></MotionSection>
    <MotionSection className="bg-surface-50 py-20 md:py-24"><div className="ars-container grid gap-12 lg:grid-cols-2"><div><SectionKicker variant="brand">SPECIFICATIONS</SectionKicker><h2 className="mt-3 font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08] text-ink-900">Specifications that ensure truly strong structures!</h2><ul className="mt-7 grid gap-4">{["Highest Corrosion Resistance CRE — 0.5% minimum", "High earthquake resistance — ductility 16 to 18%", "High strength — grade 560 N/mm² to 600 N/mm²", "High bonding with concrete through innovative angular lugs", "Higher fire resistance — FRE 0.18"].map((point) => <li key={point} className="flex gap-3 text-[14px] leading-[1.7] text-steel-700"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-brand-red" aria-hidden="true" />{point}</li>)}</ul></div><div className="relative min-h-[320px] overflow-hidden rounded-2xl bg-ink-950"><Image src="/ars-assets/TMT_Rod-CRS.png" alt="Close-up of corrosion-resistant ARS TMT steel bars" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div></div></MotionSection>
    <MotionSection className="bg-ink-950 py-20 text-white md:py-24"><div className="ars-container grid items-center gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><SectionKicker variant="light">OUR CUSTOMERS SUCCESS STORY</SectionKicker><h2 className="mt-3 font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08]">Build with confidence in ARS steel.</h2><p className="mt-5 text-[15px] leading-[1.8] text-white/70">We sell our TMT bars in a way that benefits our dealers, including the price protection scheme described in the source material.</p></div><div className="aspect-video overflow-hidden rounded-2xl border border-white/10 bg-black"><iframe className="h-full w-full" src="https://www.youtube-nocookie.com/embed/OEVnlWpos1Q" title="ARS customer success story" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div></div></MotionSection>
    <ContactCta eyebrow="ARS ENQUIRIES" headline="Ready to source ARS steel?" body="Connect with ARS for product information, buying support, or a project enquiry." primaryLabel="Request a quote" primaryHref="/request-quote" secondaryLabel="Find a dealer" secondaryHref="/our-network" />
  </main>;
}
