import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";
import { ArrowRight, Factory, FileCheck2, Recycle, Zap } from "lucide-react";
import { MotionSection } from "@/components/motion-section";
import { SectionKicker } from "@/components/section-kicker";
import { FaqList } from "@/components/faq-list";
import { SiteHeader } from "@/components/site-header";
import { createPageMetadata } from "@/lib/site-metadata";

export const metadata = createPageMetadata({ title: "Embodied Carbon, The Hidden Impact | ARS Green Steel", description: "Understand embodied carbon in construction, how material choices affect it, and why verified environmental data matters.", path: "/embodied-carbon" });

const highlights = [["40–60%", "of a building’s lifetime carbon emissions can come from its materials."], ["Front-Loaded Impact", "Material decisions made during design and procurement cannot easily be changed later."], ["Materials Matter More", "As operational energy becomes cleaner, embodied carbon takes up a larger share of a building’s total emissions."], ["Growing Focus", "Green building frameworks and investors are increasingly looking at low-embodied-carbon materials."]] as const;
const advantages = [["Recycled Steel", "Using premium-quality recyclable steel as a raw material reduces the need for new raw materials and keeps steel in use."], ["Electric Furnace", "Scrap-based electric furnace routes can use less energy than conventional steelmaking routes."], ["Renewable Energy", "Using renewable power in production can further reduce the emissions associated with making steel."], ["Measured Emissions", "Carbon performance needs to be measured and verified, not simply described as “green”."]] as const;
const advantageIcons = [Recycle, Factory, Zap, FileCheck2] as const;
const carbonTypes = [["Operational carbon", "Emissions generated while a building is being used."], ["Embodied carbon", "Emissions generated in producing and delivering the materials used to build it."]] as const;
const measurementTerms = [["LCA", "Assesses the environmental impact across the relevant stages of production."], ["EPD", "Documents the environmental performance of a product using verified data."], ["Emission Intensity", "Shows the amount of CO₂e associated with producing one tonne of finished steel."]] as const;
const faqs = [["What is embodied carbon?", "Embodied carbon is the total greenhouse gas emissions generated throughout the lifecycle of a construction material—from raw material extraction and manufacturing to transportation, fabrication, and installation. Unlike operational carbon, it is emitted before a building is occupied and cannot be reduced after construction."], ["Why is embodied carbon important in construction?", "As buildings become more energy-efficient, embodied carbon accounts for a larger share of their overall environmental impact. Choosing lower-carbon construction materials helps reduce emissions from the very beginning of a project and supports more sustainable development."], ["How does green steel help reduce embodied carbon?", "Green steel is produced using lower-emission manufacturing processes, recycled materials, and renewable energy wherever possible. By lowering the carbon intensity of steel production, it helps reduce the embodied carbon of buildings without compromising strength, durability, or performance."], ["What is an Environmental Product Declaration (EPD)?", "An Environmental Product Declaration (EPD) is an independently verified document that provides transparent information about a product's environmental impact, including its carbon emissions. It enables architects, engineers, developers, and project teams to make informed material selection decisions backed by verified data."], ["How can construction projects reduce embodied carbon?", "Reducing embodied carbon starts with smarter material choices. Selecting certified lower-carbon materials such as green steel, optimising structural design, using recycled content, and sourcing products with verified Environmental Product Declarations (EPDs) can significantly lower a project's overall carbon footprint."]] as const;

function Heading({ tag, children }: { tag: string; children: ReactNode }) { return <><SectionKicker>{tag}</SectionKicker><h2 className="mt-5 font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08] text-ink-900">{children}</h2></>; }

export default function EmbodiedCarbonPage() {
  return <main className="min-h-screen overflow-x-clip bg-white text-ink-900"><SiteHeader />
    <section className="ars-page-hero relative flex min-h-[560px] items-end overflow-hidden bg-[#060D1E] text-white md:min-h-[600px] lg:h-[680px] lg:min-h-[680px] lg:max-h-[680px]"><div className="absolute inset-0"><Image src="/ars-assets/Sustainability/EmobodiedCarbon_herobanner.jpg" alt="Construction materials and the carbon impact of the built environment" fill priority sizes="100vw" className="object-cover object-[58%_center]" /><div className="absolute inset-0 bg-gradient-to-r from-[#060D1E] via-[#060D1E]/85 to-[#060D1E]/35" /></div><div className="ars-container relative z-10 grid w-full gap-10 pb-16 pt-32 lg:grid-cols-[.74fr_.26fr] lg:items-end"><div><SectionKicker variant="light">BUILDING A LOWER-CARBON FUTURE</SectionKicker><h1 className="mt-6 max-w-5xl font-display text-[clamp(2.65rem,6vw,4.5rem)] font-black leading-[.92]">Embodied Carbon, The Hidden Impact</h1></div><p className="max-w-md text-base leading-8 text-white/75">The environmental impact of a building begins long before it is occupied—shaped by every material chosen from the ground up.</p></div></section>
    <MotionSection className="bg-white py-20 lg:py-24"><div className="ars-container"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-20"><figure className="relative min-h-[360px] overflow-hidden bg-ink-950 sm:min-h-[460px] lg:min-h-[520px]"><Image src="/ars-assets/Sustainability/WhatisGreenSteel_Banner.jpg" alt="Reinforcing steel surrounded by green vegetation, representing lower-carbon material choices" fill sizes="(min-width: 1024px) 44vw, 100vw" className="object-cover object-center" /><div className="absolute inset-y-0 left-0 w-1 bg-brand-red" aria-hidden="true" /></figure><div><Heading tag="WHAT IS EMBODIED CARBON">The Carbon Behind Construction</Heading><div className="mt-7 space-y-5 text-base leading-8 text-steel-700 lg:text-lg"><p>A building&apos;s carbon footprint does not start when people begin using it. A large portion of it is generated during the production of materials.</p><p>Embodied carbon includes the emissions related to making construction materials, from extracting and processing raw materials to manufacturing and delivering the finished products to the site.</p><p>This differs from operational carbon, which results from the daily use of a building, such as lighting, cooling, and operating equipment. Embodied carbon is mainly determined much earlier, when the materials for a project are selected and purchased.</p></div></div></div><dl className="mt-12 grid border-l border-t border-ink-900/14 md:grid-cols-2">{carbonTypes.map(([term, description], index) => <div key={term} className={`border-b border-r border-ink-900/14 p-7 md:p-8 lg:p-9 ${index === 1 ? "bg-brand-blue text-white" : "bg-surface-50"}`}><dt className={`font-display text-xl font-bold ${index === 1 ? "text-white" : "text-brand-blue"}`}>{term}</dt><dd className={`mt-3 text-base leading-7 ${index === 1 ? "text-white/74" : "text-steel-700"}`}>{description}</dd></div>)}</dl></div></MotionSection>
    <MotionSection className="bg-surface-50 py-20 lg:py-24"><div className="ars-container"><Heading tag="WHY EMBODIED CARBON MATTERS">The Carbon Impact Starts with Material Choice.</Heading><div className="mt-7 max-w-4xl space-y-5 text-base leading-8 text-steel-700 lg:text-lg"><p>A large part of a building’s carbon footprint is decided before the first brick is laid. The materials chosen at the design and procurement stage determine how much carbon is already built into the project.</p><p>As buildings become more energy efficient and electricity gets cleaner, the carbon from construction materials becomes harder to ignore. Industry standards, green building frameworks and investors are also paying closer attention to the carbon impact of the materials used.</p></div><div className="mt-12 grid border-y border-ink-900/14 md:grid-cols-2 lg:grid-cols-4">{highlights.map(([title, body]) => <article key={title} className="group border-b border-ink-900/14 py-8 transition duration-300 hover:bg-white md:px-7 lg:border-b-0 lg:border-r last:lg:border-r-0 first:md:pl-0"><h3 className="font-display text-2xl font-bold text-brand-blue transition-transform duration-300 group-hover:-translate-y-1">{title}</h3><p className="mt-4 text-sm leading-7 text-steel-700">{body}</p></article>)}</div></div></MotionSection>
    <MotionSection className="bg-white py-20 lg:py-24"><div className="ars-container grid gap-12 lg:grid-cols-[.9fr_.7fr] lg:items-center"><div><Heading tag="ROLE OF STEEL IN EMBODIED CARBON">Steel Can Make a Real Difference</Heading><div className="mt-7 space-y-5 text-base leading-8 text-steel-700 lg:text-lg"><p>Steel is a major part of modern construction. It goes into homes, commercial buildings, factories, bridges and large infrastructure projects. At the same time, making steel takes considerable energy, so it also adds to the carbon footprint of the materials used in a project.</p><p>That is why steel deserves attention when embodied carbon is being considered. Choosing a lower-carbon steel can bring down the emissions linked to the structure, especially on projects where large quantities of steel are used.</p></div><p className="mt-8 border-l-2 border-brand-red pl-6 font-display text-xl font-bold leading-8 text-ink-900">The more steel a project uses, the more its carbon intensity matters.</p></div><div className="group relative min-h-[360px] overflow-hidden bg-ink-900 sm:min-h-[480px]"><Image src="/ars-assets/homepage-manufacturing-detail.jpg" alt="ARS steel manufacturing process" fill sizes="(min-width: 1024px) 40vw, 100vw" className="object-cover opacity-90 transition duration-700 ease-out group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#060D1E]/80 via-transparent to-transparent" /><span aria-hidden="true" className="absolute bottom-0 left-0 h-1 w-1/3 bg-brand-red transition-all duration-500 group-hover:w-full" /></div></div></MotionSection>
    <MotionSection className="bg-[#0D2B6E] py-20 text-white lg:py-24"><div className="ars-container"><SectionKicker variant="light">HOW GREEN STEEL REDUCES EMBODIED CARBON</SectionKicker><h2 className="mt-5 max-w-4xl font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08]">Reducing Carbon Starts at the Steelmaking Stage</h2><div className="mt-7 max-w-4xl space-y-5 text-base leading-8 text-white/75 lg:text-lg"><p>The biggest opportunity to reduce the embodied carbon of steel comes from the way it is produced. The production route, the raw materials used and the energy behind the process all affect the final emission figure.</p><p>Green Steel can reduce this impact by combining <strong className="font-semibold text-white">recycle-based electric furnace steelmaking, lower energy usage per tonne, renewable energy and proper measurement of emissions</strong>.</p></div><div className="mt-12 grid border border-white/25 md:grid-cols-2 lg:grid-cols-4">{advantages.map(([title, body], index) => { const Icon = advantageIcons[index]; return <article key={title} className="group border-b border-white/25 p-6 transition duration-300 hover:bg-white/10 md:border-r lg:border-b-0 last:md:border-r-0"><Icon aria-hidden="true" size={22} className="text-brand-red transition-transform duration-300 group-hover:-translate-y-1 group-hover:scale-110" /><h3 className="mt-6 font-display text-xl font-bold leading-tight">{title}</h3><p className="mt-4 text-sm leading-7 text-white/72">{body}</p></article>; })}</div></div></MotionSection>
    <MotionSection className="bg-white py-20 lg:py-28">
      <div className="ars-container">
        <div className="max-w-4xl">
          <Heading tag="REAL PROJECT IMPACT">How Material Choice Changes a Project&apos;s Carbon Footprint</Heading>
          <p className="mt-7 text-base leading-8 text-steel-700 lg:text-lg">Small improvements in emission intensity create significant reductions when multiplied across an entire construction project.</p>
        </div>
        <figure className="mt-12 overflow-hidden border border-brand-blue/15 bg-surface-50">
          <div className="grid gap-5 border-b border-brand-blue/20 bg-brand-blue px-6 py-7 text-white md:grid-cols-[minmax(0,1fr)_auto] md:items-end md:px-9">
            <div>
              <p className="font-technical text-xs font-bold uppercase tracking-[0.18em] text-white/58">Embodied Carbon Impact — A Practical Example</p>
              <p className="mt-3 max-w-3xl text-sm leading-7 text-white/72"><span className="font-semibold text-white">Example:</span> To understand the real impact of material choice, consider a project consuming 10,000 tonnes of TMT rebars.</p>
            </div>
            <div className="border-l-2 border-brand-red pl-5 md:text-right">
              <p className="text-xs font-bold uppercase tracking-[0.14em] text-white/58">Project Requirement</p>
              <p className="mt-2 font-display text-2xl font-bold">10,000 tonnes of TMT steel</p>
            </div>
          </div>
          <p className="border-b border-brand-blue/15 px-6 py-4 font-technical text-xs font-bold uppercase tracking-[0.16em] text-steel-700 md:px-9">Emission Intensity Comparison</p>
          <div className="grid md:grid-cols-2">
            <div className="border-b border-brand-blue/15 p-6 md:border-b-0 md:border-r md:p-9">
              <p className="font-technical text-xs font-bold uppercase tracking-[0.16em] text-steel-700">Conventional Steel</p>
              <h3 className="mt-4 font-display text-2xl font-bold text-brand-blue">India Average Steel</h3>
              <dl className="mt-8 space-y-6">
                <div><dt className="text-xs font-bold uppercase tracking-[0.14em] text-steel-700">Emission Intensity</dt><dd className="mt-2 font-display text-3xl font-bold text-brand-blue">2.55 t CO₂e/tonne</dd></div>
                <div className="h-2 bg-[#5e626b]" aria-hidden="true" />
                <div><dt className="text-xs font-bold uppercase tracking-[0.14em] text-steel-700">Total Embodied Carbon Emissions</dt><dd className="mt-2 font-display text-3xl font-bold text-brand-blue">25,500 tCO₂e</dd></div>
              </dl>
            </div>
            <div className="border-b-4 border-green-steel bg-white p-6 md:p-9">
              <p className="font-technical text-xs font-bold uppercase tracking-[0.16em] text-green-steel">EPD Verified</p>
              <h3 className="mt-4 font-display text-2xl font-bold text-brand-blue">ARS Green Steel (EPD Verified)</h3>
              <dl className="mt-8 space-y-6">
                <div><dt className="text-xs font-bold uppercase tracking-[0.14em] text-steel-700">Emission Intensity</dt><dd className="mt-2 font-display text-3xl font-bold text-green-steel">0.592 t CO₂e/tonne</dd></div>
                <div className="h-2 bg-brand-blue/10" aria-hidden="true"><div className="h-full w-[23.2%] bg-green-steel" /></div>
                <div><dt className="text-xs font-bold uppercase tracking-[0.14em] text-steel-700">Total Embodied Carbon Emissions</dt><dd className="mt-2 font-display text-3xl font-bold text-green-steel">5,920 tCO₂e</dd></div>
              </dl>
            </div>
          </div>
          <div className="grid border-t border-brand-blue/15 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center">
            <figcaption className="border-l-4 border-brand-red bg-[#fff4f4] px-6 py-6 text-sm leading-7 text-steel-700 md:px-9"><strong className="text-brand-red-dark">Calculation Note</strong><br />Emissions calculated using emission intensity per tonne of finished steel.<br />Actual project emissions may vary based on project conditions, quantities, and system boundaries.</figcaption>
            <p className="border-t border-brand-blue/15 bg-[#e9f4ec] px-6 py-7 font-display text-xl font-bold leading-tight text-[#176534] md:px-9 lg:max-w-md lg:border-l lg:border-t-0">Potential reduction: approximately 77% lower embodied carbon from steel selection alone.</p>
          </div>
        </figure>
      </div>
    </MotionSection>
    <MotionSection className="bg-brand-blue py-20 text-white lg:py-28">
      <div className="ars-container">
        <div className="max-w-4xl">
          <SectionKicker variant="light">MEASURING EMBODIED CARBON</SectionKicker>
          <h2 className="mt-5 font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08] text-white">Measure the Carbon, Not Just the Claim</h2>
          <div className="mt-7 max-w-4xl space-y-5 text-base leading-8 text-white/74 lg:text-lg">
            <p>Knowing the carbon intensity of steel starts with measuring the emissions linked to its production. A Life Cycle Assessment (LCA) looks at the different stages involved, while an Environmental Product Declaration (EPD) presents the resulting environmental data in a standardised format.</p>
            <p>This gives project teams something concrete to work with when comparing materials. Instead of relying on a general claim that one steel is “greener” than another, they can look at the actual emission intensity and the evidence behind it.</p>
          </div>
        </div>
        <dl className="mt-12 grid border-l border-t border-white/18 md:grid-cols-3">
          {measurementTerms.map(([term, description], index) => <div key={term} className="border-b border-r border-white/18 p-7 md:p-8 lg:p-9"><span className="font-technical text-xs font-bold tracking-[0.18em] text-brand-red" aria-hidden="true">0{index + 1}</span><dt className="mt-6 font-display text-2xl font-bold leading-tight text-white">{term}</dt><dd className="mt-4 text-sm leading-7 text-white/68">{description}</dd></div>)}
        </dl>
      </div>
    </MotionSection>
    <MotionSection className="bg-surface-50 py-20 lg:py-24"><div className="ars-container max-w-4xl"><SectionKicker>FAQs</SectionKicker><FaqList className="mt-8" items={faqs.map(([question, answer]) => ({ question, answer }))} /></div></MotionSection>
    <MotionSection className="bg-brand-blue py-20 text-white lg:py-24"><div className="ars-container grid gap-10 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div className="max-w-3xl"><SectionKicker variant="light">BUILD RESPONSIBLY</SectionKicker><h2 className="mt-5 font-display text-[clamp(2rem,3.4vw,2.8rem)] font-bold leading-[1.08]">Reduce the Carbon Footprint of Your Next Project</h2><p className="mt-6 max-w-3xl text-base leading-8 text-white/75 lg:text-lg">Choose certified green steel backed by independently verified environmental performance. Talk to our team to find the right solution for your next residential, commercial, or infrastructure project.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link href="/ars-green-steel" className="focus-ring inline-flex h-12 items-center gap-2 rounded-[6px] bg-brand-red px-6 text-sm font-bold text-white transition hover:bg-brand-red-dark">Explore ARS Green Steel <ArrowRight size={16} /></Link><Link href="/green-certifications" className="focus-ring inline-flex h-12 items-center gap-2 rounded-[6px] border border-white/30 px-6 text-sm font-bold text-white transition hover:bg-white hover:text-ink-900">View Certificates <ArrowRight size={16} /></Link></div></div></MotionSection>
    </main>;
}
